{ config, ... }:
{
  flake.users.skettisouls = config.flake.lib.perSystem
    ({ system, wlib, pkgs, ... }:
    let
      inherit (config.flake) modules users;
      inherit (users.skettisouls.${system}) wrappers;
    in {
      wrappers.bash = wlib.wrapPackage {
        imports = [ modules.wrappers.bash ];
        config = {
          inherit pkgs;
          runtimePkgs = [ wrappers.eza ];
          # TODO 1: set up xdg-dirs
          bashrc.content = ''
            # generated by hm, might be important?
            [[ $- == *i* ]] || return

            HISTCONTROL=ignoredups
            HISTFILESIZE=100000
            HISTSIZE=10000
            EDITOR=nvim

            # generated by hm, might be important?
            shopt -s histappend
            shopt -s extglob
            shopt -s globstar
            shopt -s checkjobs

            alias :q=exit
            alias icat='kitten icat'
            alias l='eza -alh'
            alias l='eza -a'
            alias ls=eza
            alias lt='eza -T'
            alias cls='clear && ls'

            # Stolen from home-manager
            if test -n "$KITTY_INSTALLATION_DIR"; then
              export KITTY_SHELL_INTEGRATION="no-rc"
              source "$KITTY_INSTALLATION_DIR/shell-integration/bash/kitty.bash"
            fi
          '';
        };
      };
    });
}
