{
  flake.machines.argon.hardware = [(
    # Auto-generated by nixos-install
    { config, lib, pkgs, modulesPath, ... }:

    {
      imports =
        [ (modulesPath + "/installer/scan/not-detected.nix")
        ];

      boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
      boot.initrd.kernelModules = [ ];
      boot.kernelModules = [ "kvm-amd" ];
      boot.extraModulePackages = [ ];

      # TODO 0: Disko?
      fileSystems = {
        "/" = {
          device = "/dev/disk/by-label/NIXOS-ROOT";
          fsType = "ext4";
        };

        "/boot" = {
          device = "/dev/disk/by-label/NIXOS-BOOT";
          fsType = "vfat";
          options = [ "fmask=0077" "dmask=0077" ];
        };

        "/home/skettisouls" = {
          # Home Partition
          device = "/dev/disk/by-label/HOME";
          fsType = "btrfs";
        };

        "/home/skettisouls/Games" = {
          # 3.6T Storage Partition
          device = "/dev/disk/by-label/GAMES";
          fsType = "ext4";
          neededForBoot = false;
        };
      };

      # 48G on Games drive
      swapDevices = [{ device = "/dev/disk/by-label/SWAP"; }];

      # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
      # (the default) this is the recommended approach. When using systemd-networkd it's
      # still possible to use this option, but it's recommended to use it in conjunction
      # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
      networking.useDHCP = lib.mkDefault true;
      # networking.interfaces.enp37s0.useDHCP = lib.mkDefault true;

      nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
      hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    }
  )];
}
