{
  flake.machines.argon.hardware = [(
    # Auto-generated by nixos-install
    { config, lib, pkgs, modulesPath, ... }:

    {
      imports =
        [ (modulesPath + "/installer/scan/not-detected.nix")
        ];

      boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
      boot.initrd.kernelModules = [ ];
      boot.kernelModules = [ "kvm-amd" ];
      boot.extraModulePackages = [ ];

      fileSystems = {
        "/boot" = {
          device = "/dev/disk/by-id/ata-Samsung_SSD_870_EVO_1TB_S625NJ0R407709B-part1";
          fsType = "vfat";
          options = [ "fmask=0077" "dmask=0077" ];
        };

        "/" = {
          device = "/dev/disk/by-id/ata-Samsung_SSD_870_EVO_1TB_S625NJ0R407709B-part2";
          fsType = "ext4";
        };

        "/home/skettisouls/Games" = {
          # 3.6T Storage Partition
          device = "/dev/disk/by-id/ata-CT4000BX500SSD1_2517E9BA04F7-part1";
          fsType = "ext4";
          neededForBoot = false;
        };
      };

      swapDevices = [
        {
          # 48G Swap Partition
          device = "/dev/disk/by-id/ata-CT4000BX500SSD1_2517E9BA04F7-part2";
        }
      ];

      # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
      # (the default) this is the recommended approach. When using systemd-networkd it's
      # still possible to use this option, but it's recommended to use it in conjunction
      # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
      networking.useDHCP = lib.mkDefault true;
      # networking.interfaces.enp37s0.useDHCP = lib.mkDefault true;

      nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
      hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    }
  )];
}
